daword = [{text: 'TESLA', size: 100},
{text: 'NISSAN', size: 35},
{text: 'CHEVROLET', size: 33},
{text: 'FORD', size: 29},
{text: 'BMW', size: 27},
{text: 'KIA', size: 27},
{text: 'TOYOTA', size: 26},
{text: 'VOLKSWAGEN', size: 24},
{text: 'JEEP', size: 24},
{text: 'HYUNDAI', size: 24},
{text: 'VOLVO', size: 24},
{text: 'AUDI', size: 23},
{text: 'RIVIAN', size: 23},
{text: 'CHRYSLER', size: 23},
{text: 'MERCEDES-BENZ', size: 21},
{text: 'PORSCHE', size: 21},
{text: 'MITSUBISHI', size: 20},
{text: 'MINI', size: 20},
{text: 'POLESTAR', size: 20},
{text: 'HONDA', size: 20},
{text: 'FIAT', size: 20},
{text: 'SUBARU', size: 20},
{text: 'MAZDA', size: 20},
{text: 'SMART', size: 20},
{text: 'LEXUS', size: 20},
{text: 'LINCOLN', size: 20},
{text: 'JAGUAR', size: 20},
{text: 'CADILLAC', size: 20},
{text: 'LUCID', size: 20},
{text: 'GENESIS', size: 20},
{text: 'LAND ROVER', size: 20},
{text: 'FISKER', size: 20},
{text: 'ALFA ROMEO', size: 20},
{text: 'DODGE', size: 20},
{text: 'AZURE DYNAMICS', size: 20},
{text: 'TH!NK', size: 20},
{text: 'WHEEGO ELECTRIC CARS', size: 20},
{text: 'BENTLEY', size: 20},
{text: 'GMC', size: 20}
];
